development:
 adapter: postgresql
 encoding: unicode
 database: fwitter_dev
 host: localhost
 username: drew
 password: drew

test:
 adapter: postgresql
 encoding: unicode
 database: fwitter_test
 pool: 5
 host: localhost
 username: drew
 password: drew

production:
 adapter: postgresql
 encoding: unicode
 database: fwitter_dev
 pool: 5
 host: localhost
 username: drew
 password: drew